# 섹션 8. 비동기-동시성 프로그래밍 1

```javascript
const curry = (func) => {
  return (a, ..._) => {
    return _.length ? func(a, ..._) : (..._) => func(a, ..._);
  };
};
const isIterable = (target) => target && target[Symbol.iterator];
const checkPromise = (target, func) => {
  if (target instanceof Promise) {
    return target.then(func);
  }
  return func(target);
};

const map = curry((func, iter) => {
  let res = [];
  iter = iter[Symbol.iterator]();
  let cur;
  while (!(cur = iter.next()).done) {
    const target = cur.value;
    res.push(func(target));
  }
  return res;
});

const filter = curry((func, iter) => {
  let res = [];
  iter = iter[Symbol.iterator]();
  let cur;
  while (!(cur = iter.next()).done) {
    const target = cur.value;
    if (func(target)) {
      res.push(target);
    }
  }
  return res;
});

const reduce = curry((func, acc, iter) => {
  if (!iter) {
    iter = acc[Symbol.iterator]();
    acc = iter.next().value;
  } else {
    iter = iter[Symbol.iterator]();
  }

  return checkPromise(acc, function recursive(acc) {
    let cur;
    while (!(cur = iter.next()).done) {
      const target = cur.value;
      acc = func(acc, target);
      if (acc instanceof Promise) {
        return acc.then(recursive);
      }
    }
    return acc;
  });
});

//

const L = {};
L.range = function* (length) {
  let i = -1;
  while (++i < length) {
    yield i;
  }
};

L.map = curry(function* (func, iter) {
  iter = iter[Symbol.iterator]();
  let cur;
  while (!(cur = iter.next()).done) {
    const target = cur.value;
    yield func(target);
  }
});

L.filter = curry(function* (func, iter) {
  iter = iter[Symbol.iterator]();
  let cur;
  while (!(cur = iter.next()).done) {
    const target = cur.value;
    if (func(target)) {
      yield target;
    }
  }
});

L.flatten = function* (iter) {
  for (const target of iter) {
    if (isIterable(target)) {
      for (const deepTarget of target) {
        yield deepTarget;
      }
    }
    if (!isIterable(target)) {
      yield target;
    }
  }
};

L.deepFlat = function* f(iter) {
  for (const a of iter) {
    if (isIterable(a)) yield* f(a);
    else yield a;
  }
};

const go = (...args) => {
  return reduce((target, func) => func(target), args);
};

const pipe = (func, ...funcs) => {
  return (...args) => {
    return go(func(...args), ...funcs);
  };
};

L.flatMap = curry(pipe(L.map, L.flatten));

const take = curry((length, iter) => {
  let res = [];
  iter = iter[Symbol.iterator]();
  let cur;
  while (!(cur = iter.next()).done) {
    const target = cur.value;
    res.push(target);
    if (res.length === length) {
      return res;
    }
  }
  return res;
});

const find = curry((func, iter) =>
  go(iter, L.filter(func), take(1), ([target]) => target)
);
```

## callback과 Promise

```javascript
function addByCallback(target, callback) {
  setTimeout(() => callback(target + 1), 1000);
}

addByCallback(1, (res) => {
  addByCallback(res, (res) => {
    addByCallback(res, (res) => {
      addByCallback(res, (res) => {
        console.log("callback pattern", res);
      });
    });
  });
});

// Promise의 경우는 매개변수로 callback 함수가 필요 없음.
function addByPromise(target) {
  // return 으로 값을 다룬다는게 중요한 부분.
  return new Promise((resolve) => setTimeout(() => resolve(target + 10), 1000));
}

addByPromise(10)
  .then(addByPromise)
  .then(addByPromise)
  .then(addByPromise)
  .then((res) => console.log("promise pattern", res));
```

<br/>

## 비동기를 값으로 만드는 Promise

가장 중요한 차이는 then의 연속을 통해서 값을 꺼내볼 수 있다는 것이 아니고,<br/>
비동기 상황을 일급 값으로 다룬다는 것.

Promise는 pending, fulfilled, rejected 로 구성되어 있음.

```javascript
const callbackRes = addByCallback(1, (res) => {
  addByCallback(res, (res) => {
    addByCallback(res, (res) => {
      addByCallback(res, (res) => {
        console.log("callback pattern", res);
      });
    });
  });
});

const promiseRes = addByPromise(10)
  .then(addByPromise)
  .then(addByPromise)
  .then(addByPromise)
  .then((res) => console.log("promise pattern", res));

console.log(callbackRes); // undefined
console.log(promiseRes); // Promise { <pending> }

// addByCallback 함수와 달리 Promise를 통해 후처리를 이어갈 수 있음
```

<br/>

## 값으로서의 Promise 활용

```javascript
const delay = (target) => {
  return new Promise((resolve) => {
    return setTimeout(() => {
      resolve(target);
    }, 1000);
  });
};
const addOne = (a) => a + 1;

const checkPromise = (target, func) => {
  if (target instanceof Promise) {
    return target.then(func);
  }
  return func(target);
};

const res1 = checkPromise(10, addOne);
console.log(res1); // 11
const res2 = checkPromise(delay(10), addOne);
res2.then(console.log); // 11

checkPromise(checkPromise(10, addOne), console.log); // 11
checkPromise(checkPromise(delay(10), addOne), console.log); // 11
```

<br/>

## 합성 관점에서의 Promise와 모나드

```javascript
const funcF = (target) => target * target;
const funcG = (target) => target + 1;

console.log(funcF(funcG(1))); // 4
console.log(funcF(funcG())); // NaN(안전한 합성이 이루어지지 않음)

// 이런 것들을 해결해주는게 모나드

[1]
  .map(funcG)
  .map(funcF)
  .forEach((result) => console.log(result)); // forEach를 통해서 외부 세상의 값 변경을 이루어냄.

// 이렇게 하면 장점이 무엇?

[]
  .map(funcG) // 이 부분에서 함수가 더 이상 진행되지 않음.
  .map(funcF)
  .forEach((result) => console.log(result)); // NaN 으로 출력되지 않음.

// 이해를 돕기 위해 Array.of() 사용.
Array.of(1)
  .map(funcG)
  .map(funcF)
  .forEach((result) => console.log(result)); // forEach를 통해서 외부 세상의 값 변경을 이루어냄.

// Promise는 비동기적으로 일어나는 상황을 안전하게 합성하기 위한 도구.
Promise.resolve()
  .then(funcG)
  .then(funcF)
  .then((result) => console.log(result)); // NaN
// 안에 어떠한 값이 있는지 없는지에 대해서 안전한 상황을 추구하는게 아님
```

<br/>

## Kleisli Composition 관점에서의 Promise

들어오는 인자가 잘못되어서 함수에서 에러가 발생하거나<br/>
혹은 정확한 인자가 전달 되었어도, 외부에 대한 의존 때문에 정확한 결과를 전달할 수 없을 때 <br/>
에러가 발생하는 상황들을 해결하기 위한 목적으로써의 함수 합성.

f(g(x)) === f(g(x))<br/>
실무에서, 좌변과 우변에서의 g(x)가 다르게 평가되는 경우가 발생할 수 있음(합성이 성립되지 않음).<br/>
이러한 상황에서도 안전한 합성을 이룰 수 있도록 하는 방법이 Cleisli Composition.

f(g(x)) === g(x)<br/>
에러가 발생한 경우, g가 리턴하는 값이 f를 합성하더라도 마치 합성을 하지 않은 것처럼 동작하게 되는 것.

```javascript
const users = [
  { id: 1, name: "A" },
  { id: 2, name: "B" },
  { id: 3, name: "C" },
];

const getUserById = (id) => {
  return find((user) => user.id == id, users) || Promise.reject("없는맨");
};

const funcF = ({ name }) => name;
const funcG = getUserById;

const funcFG = (id) => funcH(funcI(id));
// 두 함수가 합성되는 순간 안전하지 않은 상황이 발생할 수 있게 된다.
// funcF는 name을 가진 객체를 받았을 때만 정상적으로 동작하고
// funcG는 내부에 결과가 있어야만 정상적으로 동작하기 때문.

console.log(funcFG(2)); // B

users.pop();
users.pop();
console.log(funcFG(2)); // undefined
```

하지만 Promise 구조를 사용한다면?<br/>
undefined와 같은 불안전한 값에 대한 접근을 막아낼 수 있음.

```javascript
const users = [
  { id: 1, name: "A" },
  { id: 2, name: "B" },
  { id: 3, name: "C" },
];

const getUserById = (id) => {
  return find((user) => user.id == id, users) || Promise.reject("없는맨");
};

const funcF = ({ name }) => name;
const funcG = getUserById;

// 실직적인 적용부
const funcPromiseFG = (id) =>
  Promise.resolve(id)
    .then(funcF)
    .then(funcG)
    .catch((target) => target);

users.pop();
users.pop();
funcPromiseFG(2).then(console.log); // 없는맨
```

<br/>

## go, pipe, reduce에서 비동기 제어

```javascript
go(
  1,
  (target) => target + 10,
  (target) => Promise.resolve(target + 100), // 특정 지점에서 비동기 상황이 발생한다면?
  (target) => target + 1000,
  console.log // [object Promise]1001000 이라는 비정상적인 값 출력
);

// reduce만 수정하면 해당 문제를 해결할 수 있다.
const checkPromise = (target, func) => {
  if (target instanceof Promise) {
    return target.then(func);
  }
  return func(target);
};

// 기존 사용하던 reduce함수를 다음과같이 수정
const reduce = curry((func, acc, iter) => {
  if (!iter) {
    iter = acc[Symbol.iterator]();
    acc = iter.next().value;
  } else {
    iter = iter[Symbol.iterator]();
  }

  // Promise가 아닐 때에는 동기적으로 while문을 통해 다음으로 넘어갈 수 있도록 구현해야 함.
  return checkPromise(acc, function recursive(acc) {
    let cur;
    while (!(cur = iter.next()).done) {
      const target = cur.value;
      acc = func(acc, target);
      if (acc instanceof Promise) {
        return acc.then(recursive);
      }
    }
    return acc;
  });
});

go(
  Promise.resolve(1), // 첫 인자로 Promise
  (target) => target + 10,
  (target) => Promise.resolve(target + 100),
  (target) => target + 1000,
  console.log // 1111
);

// Promise.reject에 대해서도 다음과같이 처리할 수 있다.
go(
  Promise.resolve(1),
  (target) => target + 10,
  (target) => Promise.reject("error 발생"), // reject. 이 이후로는 함수가 진행되지 않음.
  (target) => target + 1000,
  console.log
).catch((target) => console.log(target)); // "error 발생"
```

<br/>

## promise.then의 중요한 규칙

then 메서드를 통해 결과를 꺼냈을 때의 값이 반드시 Promise가 아니라는 것.<br/>
Promise의 깊이가 아무리 깊더라도, 반드시 프로미스 가장 안쪽에 있는 값을 꺼낸다는 것.

```javascript
Promise.resolve(Promise.resolve(Promise.resolve(1))).then(console.log); // 1

new Promise((resolve) => resolve(new Promise((resolve) => resolve(1)))).then(
  console.log // 1
);
```

<br/>
